---
# See: https://github.com/ansible/ansible/issues/64852
- block:

  - name: Ensure dnf-plugins are installed on CentOS 8+.
    yum:
      name: dnf-plugins-core
      state: present

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
